Hw01
Vlad311010/homework pull request #1
Opened 2024-10-12 10:45 UTC by Vlad311010

2024-10-15 12:10 UTC, IgorKheidorov requested changes
Totally cool, fix issues and ask for a review again

2024-10-15 12:10 UTC, IgorKheidorov commented on hw01/t1/Program.cs
> +        {
Not clear, comment is needed. I understand that 130 is minimum value with AA, by this is not fully truth )) a nd be can be negative

2024-10-15 12:10 UTC, IgorKheidorov commented on hw01/t1/Program.cs
> +            {
decimalNumber  can be negative, but this case is not proceeded

2024-10-15 12:10 UTC, IgorKheidorov commented on hw01/t1/Program.cs
> +
a can be greater then b

2024-10-15 12:10 UTC, IgorKheidorov commented on hw01/t1/Program.cs
> +                if (aCounter == 2)
Then the application displays all integers in the range from a (inclusive) to b (inclusive), it's supposed to output value is decimal form (just Console.WriteLine(decimalNumber))

2024-10-15 12:10 UTC, IgorKheidorov commented on hw01/t1/Program.cs
> +            StringBuilder stringBuilder = new StringBuilder();
for(int decimallNumber = a; decimalNumber <=b; decimalNumber++)

2024-10-15 12:10 UTC, IgorKheidorov commented on hw01/t2/Program.cs
> +
What about  remainder=0 ? (for example, checkSum= 22). Please fix

2024-10-20 15:24 UTC, Vlad311010 commented on hw01/t2/Program.cs
> +
fixed in [b79bbf7](https://github.com/Vlad311010/homework/pull/1/commits/b79bbf7db295c6fec1711aceb4f46d0a84a1c37e)

2024-10-20 15:24 UTC, Vlad311010 commented on hw01/t1/Program.cs
> +        {
fixed in [cdbf4a1](https://github.com/Vlad311010/homework/pull/1/commits/cdbf4a14117a1e467cf8696832f533825c749aa2)

2024-10-20 15:24 UTC, Vlad311010 commented on hw01/t1/Program.cs
> +            {
fixed in [cdbf4a1](https://github.com/Vlad311010/homework/pull/1/commits/cdbf4a14117a1e467cf8696832f533825c749aa2)

2024-10-20 15:24 UTC, Vlad311010 commented on hw01/t1/Program.cs
> +
fixed in [cdbf4a1](https://github.com/Vlad311010/homework/pull/1/commits/cdbf4a14117a1e467cf8696832f533825c749aa2)

2024-10-20 15:24 UTC, Vlad311010 commented on hw01/t1/Program.cs
> +                if (aCounter == 2)
fixed in [cdbf4a1](https://github.com/Vlad311010/homework/pull/1/commits/cdbf4a14117a1e467cf8696832f533825c749aa2)

2024-10-20 15:24 UTC, Vlad311010 commented on hw01/t1/Program.cs
> +            StringBuilder stringBuilder = new StringBuilder();
fixed in [cdbf4a1](https://github.com/Vlad311010/homework/pull/1/commits/cdbf4a14117a1e467cf8696832f533825c749aa2)

2024-10-21 12:57 UTC, IgorKheidorov approved these changes

2024-10-26 10:03 UTC, merged