Hw05
Vlad311010/homework pull request #5
Opened 2024-11-13 12:16 UTC by Vlad311010

2024-11-14 11:58 UTC, IgorKheidorov requested changes
Pleas fix comments

2024-11-14 11:58 UTC, IgorKheidorov commented on HW05/t1/SparseMatrixEnum.cs
> +
As I see it is not used, seems that some experiments )) Please remove

2024-11-14 11:58 UTC, IgorKheidorov commented on HW05/t1/SparseMatrix.cs
> +
Dictionary<(int, int), long>, more clear and simple. Or at least use name MatrixIndex**es**

2024-11-14 11:58 UTC, IgorKheidorov commented on HW05/t1/SparseMatrix.cs
> +            {
Check indexes for outofrange

2024-11-14 11:58 UTC, IgorKheidorov commented on HW05/t1/SparseMatrix.cs
> +            set
If you set 0 to the element which was not 0 before please remove it

2024-11-14 11:58 UTC, IgorKheidorov commented on HW05/t1/SparseMatrix.cs
> +                    long value = 0;
use indexer here

2024-11-14 11:58 UTC, IgorKheidorov commented on HW05/t2/ISBN13.cs
> +        {
Move to const not to create objects each time

2024-11-14 11:58 UTC, IgorKheidorov commented on HW05/t2/ISBN13.cs
> +{
Cool

2024-11-14 11:58 UTC, IgorKheidorov commented on HW05/t2/Catalog.cs
> +            {
throw an exception if no key,better use TryGetValue here and return null

2024-11-14 11:58 UTC, IgorKheidorov commented on HW05/t2/Catalog.cs
> +                .Select(KeyValue => KeyValue.Value.Authors)
Better to use GroupBy here

2024-11-17 15:43 UTC, Vlad311010 commented on HW05/t1/SparseMatrixEnum.cs
> +
using statement is required for 
https://github.com/Vlad311010/homework/blob/70820679348d484ace66ed75de85e17c712398a5/HW05/t1/SparseMatrixEnum.cs#L25-L31

2024-11-19 14:09 UTC, merged