Hw06
Vlad311010/homework pull request #7
Opened 2024-11-19 14:30 UTC by Vlad311010

Because of project structure changes some files (Book.cs, Catalog.cs) treated as new files

2024-11-19 14:46 UTC, Vlad311010 commented on HW05/t2/Repositories/XMLRepositoty.cs
> +    }
What is better in this case? 
1. To throw new exception like in line 37.
2. To rethrow exception like 
```
catch (FileNotFoundException ex)
{
    throw;
}
```

2024-11-29 07:52 UTC, IgorKheidorov requested changes
Totally ok, the idea is implemented correctly, please fix comments

2024-11-29 07:52 UTC, IgorKheidorov commented on HW05/t2/Repositories/IRepository.cs
> +    {
filename has to be a property of Repository, not the part of interface
Change to public void Serialize(T catalog);

2024-11-29 07:52 UTC, IgorKheidorov commented on HW05/t2/Repositories/XMLRepositoty.cs
> +    }
Better not to catch exception here, because you do nothing by this code -> catch and throw the same type of exception. Remove filePath from interface declaration, this is the part of repository (see the perv comment)

2024-11-29 07:52 UTC, IgorKheidorov commented on HW05/t2/Library/Book.cs
> +
Not bad idea but the Book (and other entities has not to know about serialization models. Move this conversion to serialization models.

2024-11-29 07:52 UTC, IgorKheidorov commented on HW05/t2/Repositories/XMLRepositoty.cs
> +{
XMLRepository, check grammar

2024-12-02 12:56 UTC, IgorKheidorov requested changes
Please fix the issue to follow the reqiurements  for json (one file-one author with all his books)

2024-12-10 10:28 UTC, IgorKheidorov approved these changes
Cool enough, please look comment and merge

2024-12-10 10:28 UTC, IgorKheidorov commented on HW05/t2/Program.cs
> +
IRepository repository= new XMLRepository();, 
then
 repository = new JsonRepository(); 
use the same variable, this is the idea of interface usage )))

2024-12-12 14:38 UTC, merged